### ISSUE TITLE
Support base64 filename in Content-Disposition

### ISSUE THREAD

**Issue by jdesboeufs** [inspireteam/link-analyzer#1]
Use case: Microsoft Azure Blob Storage

Example:

```
Content-Disposition: attachment; filename="=?utf-8?B?TGVzIGPDomJsZXMgb3B0aXF1ZXMuemlw?="
```

Expected decoded filename:

```
Les câbles optiques.zip
```

cc @Guts

**Comment by Guts** [comment]
Cc @mcartoixa

**Comment by mcartoixa** [comment]
FYI : cet encodage n'est pas lié à Azure Blob Storage.
http://greenbytes.de/tech/tc2231/#encoding-2047

**Comment by jdesboeufs** [comment]
Thx!
